# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xts < Formula
  desc "xts is a script that generates an insert statement from a mysql xml dump file."
  homepage "https://genkiroid.github.io/"
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/genkiroid/xts/releases/download/v0.1.1/xts_0.1.1_darwin_amd64.tar.gz"
      sha256 "11d94e6781559e33fb586a8bfe306a547861a57d3db17bca378fb850203ce6eb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/genkiroid/xts/releases/download/v0.1.1/xts_0.1.1_darwin_arm64.tar.gz"
      sha256 "c74f5d5725d855be2b2d70f442bda81ce780e77e23abf28a4191ff309a330f9f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/genkiroid/xts/releases/download/v0.1.1/xts_0.1.1_linux_amd64.tar.gz"
      sha256 "544a3c461f7e8b44ab3f5e839b09ecbaf711770efdec26fdd6c567fa8b323d04"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/genkiroid/xts/releases/download/v0.1.1/xts_0.1.1_linux_arm64.tar.gz"
      sha256 "78d4dbb6a25186634f73d07ae278345a544f38c115fa4702714971ed26dfff35"
    end
  end

  def install
    bin.install "xts"
  end
end
