# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xts < Formula
  desc "xts is a script that generates an insert statement from a mysql xml dump file."
  homepage "https://genkiroid.github.io/"
  version "0.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/genkiroid/xts/releases/download/v0.0.1/xts_0.0.1_darwin_amd64.tar.gz"
      sha256 "bc8c409d82d0fc7bc8a55fe2bc24c90e3b7d783179ebde1743ae88f876ac2fd5"
    end
    if Hardware::CPU.arm?
      url "https://github.com/genkiroid/xts/releases/download/v0.0.1/xts_0.0.1_darwin_arm64.tar.gz"
      sha256 "35bc0d257e9098a4decdf7410db06c477aee8e492673830c9e92dbb31e8f3261"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/genkiroid/xts/releases/download/v0.0.1/xts_0.0.1_linux_amd64.tar.gz"
      sha256 "d16d3385233f7c014f8ee1428ade80064c6260310e8cb36956e2287cf2783610"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/genkiroid/xts/releases/download/v0.0.1/xts_0.0.1_linux_arm64.tar.gz"
      sha256 "223e39e1673d8e49857db6587393a1e696dbc42f03392158b9e3bacd83c1f747"
    end
  end

  def install
    bin.install "xts"
  end
end
