# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xts < Formula
  desc "xts is a script that generates an insert statement from a mysql xml dump file."
  homepage "https://genkiroid.github.io/"
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/genkiroid/xts/releases/download/v0.2.0/xts_0.2.0_darwin_amd64.tar.gz"
      sha256 "10926ad6bc9ec1b59390f5a38e8bdcd26feda9931fec742dce676b6bb0d5898e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/genkiroid/xts/releases/download/v0.2.0/xts_0.2.0_darwin_arm64.tar.gz"
      sha256 "a3df8fd7d2419376b6709e928ddd4f19dab77bd8f12b75d97ae31431253ea0f2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/genkiroid/xts/releases/download/v0.2.0/xts_0.2.0_linux_amd64.tar.gz"
      sha256 "f5aff8a768acda2eece20524a7f50a52892d8bdbbfacfd10dad8c0cd06339634"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/genkiroid/xts/releases/download/v0.2.0/xts_0.2.0_linux_arm64.tar.gz"
      sha256 "d5dcaeef6b4df47b656682d0eb4771911c6720ff944493ea9886dc662cef78a3"
    end
  end

  def install
    bin.install "xts"
  end
end
